name: Build
on:
  push:
    branches: ['**']
  pull_request:

env:
  addon_id: skin.contuary

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build zip
        run: ./build.sh "${{ github.workspace }}/artifacts"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.addon_id }}
          path: ${{ github.workspace }}/artifacts/*.zip
